### ISSUE TITLE
hCaptcha does not appear in Kadence forms

### ISSUE THREAD

**Issue by zero2webmaster** [hCaptcha/hcaptcha-wordpress-plugin#271]
Hi, 
I cannot get the hCaptcha to appear on a Kadence form even though that option is enabled in settings. It works fine in Fluent Forms. Any suggestions? Thank you!

**Comment by kagg-design** [comment]
Hi @zero2webmaster,

Currently, to make hCaptcha work, you need:
 - put a simple (not advanced) form on the page
 - add Google reCaptcha to the form
 - select V2
 - add keys
 - save block and form

It is messy and tedious, I agree. hCaptcha for Kadence was initially requested to replace the existing Google reCaptcha. Now I am working on making Captcha work without all the above steps. It should be released in the next v3.3.0 version.

**Comment by zero2webmaster** [comment]
Thank you! I will wait for 3.3.0

**Comment by kagg-design** [comment]
Complete support added to v3.3.0:

- In Standard Form, reCaptcha is not replaced by hCaptcha if added
- In Standard Form, hCaptcha is auto-added if reCaptcha is not in the form
- In Advanced Form, hCaptcha is replaced by our plugin hCaptcha, because we offer more settings
- In Advanced Form, Kadence hCaptcha settings are blocked with the link to settings in our plugin
- In Advanced Form, hCaptcha is auto-added if reCaptcha is not in the form
