### ISSUE TITLE
Bricks Integration

### ISSUE THREAD

**Issue by Rich-DB** [hCaptcha/hcaptcha-wordpress-plugin#279]
Integration with Bricks would be awesome :)

Website: https://bricksbuilder.io/
Form: https://academy.bricksbuilder.io/article/form-element/

Over a year ago I added it to Brick's idea board/requests but it hasn't been a priority for them over other features: https://bricksbuilder.io/ideas/#5256

**Comment by pweiss70** [comment]
Yes would be great to have!

**Comment by kagg-design** [comment]
Bricks is a premium product. Could you share it with me for testing at my email info@kagg.eu?

**Comment by kagg-design** [comment]
Trying gives me nothing. I need to see Bricks code to make the integration.

**Comment by pweiss70** [comment]
I don't think sharing a license like this is allowed. Could you please contact the bricks team here: https://bricksbuilder.io/contact/

**Comment by christoskaterini** [comment]
I have a license of bricks. How can I help you. Christos KanotidisThe content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.9 Οκτ 2023, 9:45 μμ, ο χρήστης «pweiss70 ***@***.***>» έγραψε:﻿
I don't think sharing a license like this is allowed. Could you please contact the bricks team here: https://bricksbuilder.io/contact/

**Comment by Rich-DB** [comment]
It should actually be all good - thanks!
Looks like they're adding it in 1.9.2: https://academy.bricksbuilder.io/article/form-element/#hcaptcha

**Comment by christoskaterini** [comment]
Good morning ☀️ Yes I know. That’s why I didn’t reply. Have a nice day Christos KanotidisThe content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.16 Οκτ 2023, 10:08 πμ, ο χρήστης «Rich ***@***.***>» έγραψε:﻿
It should actually be all good - thanks!
Looks like they're adding it in 1.9.2: https://academy.bricksbuilder.io/article/form-element/#hcaptcha

**Comment by kagg-design** [comment]
Closed as done natively.
