### ISSUE TITLE
WooCommerce Wishlist Implementation No Longer Works on v 1.5.1

### ISSUE THREAD

**Issue by bowen-dev406** [hCaptcha/hcaptcha-wordpress-plugin#29]
I updated this plugin from 1.4.2 to 1.5.1. I'm using WooCommerce Wishlist v 2.2.0.

When using v 1.5.1, the hCaptcha element no longer appears on the form. This happens with and without the addendum to create-a-list.php recommended in v 1.4.2.

Using hCaptcha v 1.4.2 with Wishlist v 2.2.0 works fine.

**Comment by wuniversales** [comment]
I agree with you, I'm using the old version, let's see if they fix it :(

**Comment by e271828-** [comment]
@plexusllc-admin Would you like to take this on?

**Comment by pjv** [comment]
@e271828- it looks to me like @thinhbuzz removed (in e955d415) essentially all of the functionality that [my original patch](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/19) added to hcaptcha-wordpress-plugin. I can see from the comment on the commit that the idea was to DRY the code, but two things:

1. the code that actually does something now is very far away - i looked at v 1.5.1 in vscode and had to "Go to Definition" 4 times before i saw the code that is run instead of the code that I originally committed in the file `wc_wl/wc-wl-create-list.php`. i think it would be very hard to test and debug where the problem lies through all those additional function calls.

2. the code that is now being run (after 4 additional function calls) in `common/request.php` does not do the same thing that my original code did.

Maybe @thinhbuzz could take a look at why his changes broke my woocommerce wishlists integration?

**Comment by plexusllc-admin** [comment]
@e271828- it looks to me like @thinhbuzz removed (in e955d415) essentially all of the functionality that [my original patch](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/19) added to hcaptcha-wordpress-plugin. I can see from the comment on the commit that the idea was to DRY the code, but two things:

1. the code that actually does something now is very far away - i looked at v 1.5.1 in vscode and had to "Go to Definition" 4 times before i saw the code that is run instead of the code that I originally committed in the file `wc_wl/wc-wl-create-list.php`. i think it would be very hard to test and debug where the problem lies through all those additional function calls.

2. the code that is now being run (after 4 additional function calls) in `common/request.php` does not do the same thing that my original code did.

Maybe @thinhbuzz could take a look at why his changes broke my woocommerce wishlists integration?

**Comment by kagg-design** [comment]
@plexusllc-admin @thinhbuzz @e271828- I am fixing the issue right now.

**Comment by kagg-design** [comment]
@plexusllc-admin @thinhbuzz @e271828- Fixed in https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/35. No code is needed in theme/woocommerce folder anymore.

**Comment by e271828-** [comment]
@bowen-dev406 or @wuniversales can you confirm this branch works for you?

**Comment by plexusllc-admin** [comment]
@kagg-design Awesome - looking forward to testing when I have a minute.

**Comment by plexusllc-admin** [comment]
@kagg-design that is a very clever trick with the `ob_start` and `ob_get_clean` in the before and after wcwl actions.

Unfortunately, it's not working on my site. I get no hcaptcha rendered in the create wishlist form.

![2020-07-07 at 10 14 AM](https://user-images.githubusercontent.com/16086676/86803087-49ae8900-c03b-11ea-8613-3795ea7497d7.jpg)

**Comment by kagg-design** [comment]
I have tested on my site, and it did work. Could you send the WooCommerce Wishlist plugin to me by email info@kagg.eu, as I am not sure I have the latest version?

Looking at the picture, I do not understand how this could be. `preg_replace` should find the last `<p class="form-row">` (in which submit button is), and insert hcaptcha between `</p>` and `<p class="form-row">`.

Please see how it works.

![image](https://user-images.githubusercontent.com/28291450/86810174-51931b00-c085-11ea-8e05-b1500aa0dc55.png)

Don't you forget to check appropriate box in plugin settings?

**Comment by plexusllc-admin** [comment]
@kagg-design No, I have the checkbox checked.

![2020-07-07 at 11 18 AM](https://user-images.githubusercontent.com/16086676/86811624-bcbbfd80-c043-11ea-82ea-995a2681253e.jpg)

I see I mis-read the code and thought it was matching the row above the button row, but in any case, it is not rendering the hcpatcha before the button row either as you can see in my screenshot above.

Your email host will not allow me to send you the plugin. 

<info@kagg.eu>: host aspmx.l.google.com[2607:f8b0:4001:c12::1a] said: 552-5.7.0
   This message was blocked because its content presents a potential 552-5.7.0
   security issue. Please visit 552-5.7.0

I tried re-naming it so it wasn't a zip file anymore and it still wouldn't go.

The current version of the plugin is 2.2.0. The actions `woocommerce_wishlists_before_wrapper` and `woocommerce_wishlists_after_wrapper` are there in the `create-a-list.php` file. I agree that it looks like the `preg_replace` should be finding `<p class="form-row">` and adding the hcapture.

**Comment by kagg-design** [comment]
@plexusllc-admin could you share the plugin somewhere on the Google drive or DropBox? It is the premium plugin, and I found version 2.1.4 only.

**Comment by kagg-design** [comment]
@plexusllc-admin Thank you, I have activated 2.2.0, and the same - it works for me. Does plugin has proper slug - wp-content/plugins/woocommerce-wishlists/woocommerce-wishlists.php ?

What if to print something in the beginning of the `wc-wl-create-list.php`? What if to print something after `echo $wrapper;` ?

**Comment by plexusllc-admin** [comment]
i see what the problem is, I think. @kagg-design please download the plugin that is being served from the [wp plugins server](https://wordpress.org/plugins/hcaptcha-for-forms-and-more/) and check the `wc-wl-create-list.php` file in that package.

**Comment by kagg-design** [comment]
@plexusllc-admin I do not understand your comment. We discuss here the fix I made in https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/35

What do you mean? On the wp.org, this file is wrong.

**Comment by plexusllc-admin** [comment]
@kagg-design the plugin on wp.org was updated to version 1.5.2 right after your fix was merged and I have been assuming that the fix was included in 1.5.2. Is that not correct?

**Comment by kagg-design** [comment]
@plexusllc-admin no, it is not correct. Today, I have made 3 PRs: for CF7, for Wishlist, and for text domain. Only the first one (CF7, https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/34) was merged.

**Comment by plexusllc-admin** [comment]
argggg. Sorry!

I just tested your code from the repo and it works perfectly.
