### ISSUE TITLE
Captcha error in Wordpress

### ISSUE THREAD

**Issue by Choups13** [hCaptcha/hcaptcha-wordpress-plugin#299]
Hello, 

We are using Hcaptcha for our forms on our website based on Wordpress. 
To create these forms we are using WPForm plugin. 
Since several days we are facing an issue : Hcaptcha doesn’t working and people can’t contact us. 
Here is the error : 
![captcha 1](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/153498271/6dc44414-c185-4249-b641-055cf01dc4d4)

 

I’ve tried to to add with this field : 
![captcha 2](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/153498271/ec9c4825-b821-4486-b4b0-a01341d6b2ac)

    or even by adding HTML code :  
![captcha 3](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/153498271/b30ce399-c61c-4dc7-9259-4661d877920c)

It’s working for some time and came to error with no idea. 
Any idea how to configure it ? 
 Thanks

**Comment by kagg-design** [comment]
You should not use HTML code in WPForms. It has good support for hCaptcha.

Your problem is related to the JS error. Open the console of your browser, and you will see it. After an error happens, further JS code can not be executed anymore, and hCaptcha is not rendered. What you see is just a placeholder image, which must be replaced by rendered hCaptcha widget.

**Comment by Choups13** [comment]
Thanks for your help. Limitation was due to CSP. 
Thanks
