### ISSUE TITLE
Forminator: hCaptcha not displaying on front end

### ISSUE THREAD

**Issue by whynotadv** [hCaptcha/hcaptcha-wordpress-plugin#363]
Hi Support,

I have a client site that I'm frustrated with, They are my biggest client and their form builder is called forminator by WPMUDev and they have integration with the free version of hCaptcha. That being said, I followed the instructions just like I did for another site that I use hCaptcha and it will only load on the backend and not the front end.

For example, I see the hCaptcha in the forminator preview but not when I view the actual form on the page. I was wondering if you could analyze the page and web browser console/network and tell me what could be the problem?

I use [bunny.net](http://bunny.net/) CDN but no other caching method and I've cleared the cache several times already.

https://jamyershomes.com/contact-us is the problematic page, however, I created a separate test to see if it's happening everywhere and it's doing it here too: https://jamyershomes.com/test-contact-page/

I switched from Google ReCaptcha because it wasn't working the greatest and now this hCaptcha product won't even load.

I've also reached out to advanced product support at InMotion Hosting but they so far haven't found anything on their end.

Thanks!

**Comment by kagg-design** [comment]
Hi @whynotadv,

The problem is that some styling exists on your website.

![image](https://github.com/user-attachments/assets/22731c11-ac14-4ef0-8605-8d92148a0dcb)

The Captcha is created (see iframe) but hidden by the `.forminator-hcaptcha-left {display: none;}`.

When I turn off this rule in the browser, I see Captcha.

![image](https://github.com/user-attachments/assets/23d7d0d3-f6ea-441b-ba6f-3b7b14a4fe32)

This style `.forminator-hcaptcha-left` is not from our plugin or Forminator plugin; it is generated by your website's custom code and added to the page as an inline style.

![image](https://github.com/user-attachments/assets/ea14fefd-e455-4181-b374-cb78a3cfe1dc)

It looks like a leftover after using reCaptcha. You should find where it is added and remove it.

**Comment by whynotadv** [comment]
Hi Igor,

I completely forgot about that styling alteration and thought it was
specific only to reCaptcha. I was wrong! Wow, thank you!

**Comment by whynotadv** [comment]
Sorry here's my screenshot...
<img width="987" alt="Screenshot 2024-10-15 at 9 35 12 AM" src="https://github.com/user-attachments/assets/e5915474-e8f4-4e3f-b037-ecfcea8c3d35">

**Comment by kagg-design** [comment]
The message appears when this setting is on.

![image](https://github.com/user-attachments/assets/6f54a3e1-edcd-4dfb-9fab-4ac89e99d671)

**Comment by whynotadv** [comment]
Ok Thank you but I don’t know what that means?  I’m not using reCAPTCHA
anymore.

**Comment by kagg-design** [comment]
This setting is needed in some particular cases. You can safely turn it off, and the console message will disappear.
