### ISSUE TITLE
Wp Fluent Forms integration

### ISSUE THREAD

**Issue by Jordidriesen** [hCaptcha/hcaptcha-wordpress-plugin#52]
Since it's a plugin that's getting popular, it would be nice to use hcaptcha on it.

**Comment by kagg-design** [comment]
Thank you for the PR!

The problem was here: you had to replace `hcaptcha_fluent_status` with `hcaptcha_fluent_status`, as it is the option name.

Please see [this commit](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/138/commits/a2d4f523e93d01a18e69243789c4ad69e4e271ee).

Please also check the [code cleanup](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/138/commits/1887179b56fcd8d09960320bbeb7707ecf4d0e1a) commit.

**Comment by kagg-design** [comment]
Published in 1.13.3
